-- Generated by https://pgtune.leopard.in.ua/
-- WARNING this tool not being optimal for very high memory systems
-- ALTER SYSTEM writes the given parameter setting to the postgresql.auto.conf file,
-- which is read in addition to postgresql.conf and
-- restart database
-- DB Version: 14
-- OS Type: linux
-- DB Type: oltp
-- Total Memory (RAM): 162 GB
-- CPUs num: 32
-- Data Storage: ssd

ALTER SYSTEM SET
 max_connections = '300';
ALTER SYSTEM SET
 shared_buffers = '41472MB';
ALTER SYSTEM SET
 effective_cache_size = '124416MB';
ALTER SYSTEM SET
 maintenance_work_mem = '2GB';
ALTER SYSTEM SET
 checkpoint_completion_target = '0.9';
ALTER SYSTEM SET
 wal_buffers = '16MB';
ALTER SYSTEM SET
 default_statistics_target = '100';
ALTER SYSTEM SET
 random_page_cost = '1.1';
ALTER SYSTEM SET
 effective_io_concurrency = '200';
ALTER SYSTEM SET
 work_mem = '35389kB';
ALTER SYSTEM SET
 min_wal_size = '2GB';
ALTER SYSTEM SET
 max_wal_size = '8GB';
ALTER SYSTEM SET
 max_worker_processes = '32';
ALTER SYSTEM SET
 max_parallel_workers_per_gather = '4';
ALTER SYSTEM SET
 max_parallel_workers = '32';
ALTER SYSTEM SET
 max_parallel_maintenance_workers = '4';
